name: Release Creation

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 📡 Checkout
        uses: actions/checkout@v2

      # Substitute the Manifest and Download URLs in the module.json
      - name: 🔧 Substitute Manifest and Download Links For Versioned Ones
        id: sub_manifest_link_version
        uses: microsoft/variable-substitution@v1
        with:
          files: 'system.json'
        env:
          version: ${{github.event.release.tag_name}}
          manifest: https://raw.githubusercontent.com/stefouch/t2k4e/master/system.json
          download: https://github.com/${{github.repository}}/releases/download/${{github.event.release.tag_name}}/master.zip

      # create a zip file with all files required by the module to add to the release
      - name: 🔧 Creates ZIP Archive
        run: zip -r ./master.zip system.json template.json README.md LICENSE t2k4e.css t2k4e.js assets/ fonts/ lang/ lib/ module/ templates/

      # Create a release for this specific version
      - name: 🚩 Update Release with Files
        id: create_version_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true # set this to false if you want to prevent updating existing releases
          name: ${{ github.event.release.name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json, ./master.zip'
          tag: ${{ github.event.release.tag_name }}
          body: ${{ github.event.release.body }}

      # Update the 'latest' release
      - name: 🚀 Create Release
        id: create_latest_release
        uses: ncipollo/release-action@v1
        if: endsWith(github.ref, 'master')
        with:
          allowUpdates: true
          name: Latest
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: './system.json,./master.zip'
          tag: latest
          body: ${{ github.event.release.body }}